project:
  type: website

website:
  title: "coltonquirk"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
  repo-url: https://github.com/coltonquirk

format:
  html:
    theme:
        light: united 
        dark:  cyborg 
    css: styles.css
    toc: true

