project:
  type: website

website:
  title: "coltonquirk"
  favicon: "logo.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - tutoring.qmd
      - resume.qmd
  repo-url: https://github.com/coltonquirk

format:
  html:
    theme:
        light: 
          - flatly 
          # - _extensions/catppuccin/latte.scss
        dark:
          - darkly 
          # - _extensions/catppuccin/mocha.scss
    css: styles.css
    toc: true

execute:
  freeze: auto
